In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("HREmployee.csv")

In [5]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [6]:
# 2. Display the first 10 records.
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [7]:
# 3. Display the last 10 records.
df.tail(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1460,29,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,...,2,80,0,5,3,1,5,4,0,4
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [8]:
# 4. Find the number of rows and columns.
df.shape

(1470, 35)

In [9]:
# 5. Display all column names.
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [10]:
# 6. Check the data type of each column.
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

Questions

In [11]:


# 1. How many records are present in the dataset?
df.shape

# There are 1470 records (rows) and 35 columns in the dataset.

(1470, 35)

In [12]:
# 2. How many features are available?
df.shape[1]

35

In data science, features = columns (excluding the target column in some contexts, but in basic EDA we usually count all columns).

There are 35 features (columns) available in the dataset.

In [13]:
# 3. Which columns are numerical?
df.select_dtypes(include='number').columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [14]:
# to get in list
list(df.select_dtypes(include='number').columns)

['Age',
 'DailyRate',
 'DistanceFromHome',
 'Education',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [15]:
# to get count
len(df.select_dtypes(include='number').columns)

26

In [16]:
# 4. Which columns are categorical?
df.select_dtypes(include='object').columns

Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'Over18', 'OverTime'],
      dtype='object')

In [17]:
# Task 1.2: Dataset Overview

# Generate:
# Dataset summary
# Statistical summary
# Information summary
# Questions

In [18]:
# 1. Which feature has the highest average value?
df.select_dtypes(include='number').mean().sort_values(ascending=False)

MonthlyRate                 14313.103401
MonthlyIncome                6502.931293
EmployeeNumber               1024.865306
DailyRate                     802.485714
StandardHours                  80.000000
HourlyRate                     65.891156
Age                            36.923810
PercentSalaryHike              15.209524
TotalWorkingYears              11.279592
DistanceFromHome                9.192517
YearsAtCompany                  7.008163
YearsInCurrentRole              4.229252
YearsWithCurrManager            4.123129
PerformanceRating               3.153741
Education                       2.912925
TrainingTimesLastYear           2.799320
WorkLifeBalance                 2.761224
JobInvolvement                  2.729932
JobSatisfaction                 2.728571
EnvironmentSatisfaction         2.721769
RelationshipSatisfaction        2.712245
NumCompaniesWorked              2.693197
YearsSinceLastPromotion         2.187755
JobLevel                        2.063946
EmployeeCount                   1.000000
StockOptionLevel                0.793878
dtype: float64

In [19]:
df.select_dtypes(include='number').mean().idxmax()

'MonthlyRate'

In [20]:
means = df.select_dtypes(include='number').mean()

print("Feature:", means.idxmax())
print("Average:", means.max())

Feature: MonthlyRate
Average: 14313.103401360544

In [24]:
# 2. Which feature has the highest standard deviation?
df.select_dtypes(include='number').std().sort_values(ascending=False)

MonthlyRate                 7.117786e+03
MonthlyIncome               4.707957e+03
EmployeeNumber              6.020243e+02
DailyRate                   4.035091e+02
HourlyRate                  2.032943e+01
Age                         9.135373e+00
DistanceFromHome            8.106864e+00
TotalWorkingYears           7.780782e+00
YearsAtCompany              6.126525e+00
PercentSalaryHike           3.659938e+00
YearsInCurrentRole          3.623137e+00
YearsWithCurrManager        3.568136e+00
YearsSinceLastPromotion     3.222430e+00
NumCompaniesWorked          2.498009e+00
TrainingTimesLastYear       1.289271e+00
JobLevel                    1.106940e+00
JobSatisfaction             1.102846e+00
EnvironmentSatisfaction     1.093082e+00
RelationshipSatisfaction    1.081209e+00
Education                   1.024165e+00
StockOptionLevel            8.520767e-01
JobInvolvement              7.115611e-01
WorkLifeBalance             7.064758e-01
PerformanceRating           3.608235e-01
EmployeeCount               1.110601e-16
StandardHours               0.000000e+00
dtype: float64

In [25]:
stds = df.select_dtypes(include='number').std()

print("Feature:", stds.idxmax())
print("Standard Deviation:", stds.max())

Feature: MonthlyRate
Standard Deviation: 7117.786044059973

Variability is measured using standard deviation.

In [ ]:
# 3. Which feature has the minimum variability?
df.select_dtypes(include='number').std().sort_values()

StandardHours               0.000000e+00
EmployeeCount               1.110601e-16
PerformanceRating           3.608235e-01
WorkLifeBalance             7.064758e-01
JobInvolvement              7.115611e-01
StockOptionLevel            8.520767e-01
Education                   1.024165e+00
RelationshipSatisfaction    1.081209e+00
EnvironmentSatisfaction     1.093082e+00
JobSatisfaction             1.102846e+00
JobLevel                    1.106940e+00
TrainingTimesLastYear       1.289271e+00
NumCompaniesWorked          2.498009e+00
YearsSinceLastPromotion     3.222430e+00
YearsWithCurrManager        3.568136e+00
YearsInCurrentRole          3.623137e+00
PercentSalaryHike           3.659938e+00
YearsAtCompany              6.126525e+00
TotalWorkingYears           7.780782e+00
DistanceFromHome            8.106864e+00
Age                         9.135373e+00
HourlyRate                  2.032943e+01
DailyRate                   4.035091e+02
EmployeeNumber              6.020243e+02
MonthlyIncome               4.707957e+03
MonthlyRate                 7.117786e+03
dtype: float64

In [28]:
stds = df.select_dtypes(include='number').std()

print("Feature:", stds.idxmin())
print("Standard Deviation:", stds.min())

Feature: StandardHours
Standard Deviation: 0.0

Part 2: Data Quality Assessment

Task 2.1: Missing Values Analysis

Calculate:
Total missing values
Percentage of missing values
Create:
Missing value table
Missing value bar chart
Questions

The dataset contains no missing values

In [34]:
# 1. Which column contains the most missing values?
df.isna().sum().max()

0

In [37]:
# 2. Which columns have no missing values?
df.columns[df.isna().sum() == 0]

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
# # 3. How can missing values affect Machine Learning models?


# Training errors 🚫
# Many algorithms (e.g., Linear Regression, SVM, Logistic Regression) cannot handle missing values directly and may throw errors.
# Reduced accuracy 📉
# Missing data can hide important patterns, leading to poor predictions.
# Biased results ⚠️
# If missing values are concentrated in certain groups, the model may learn incorrect relationships.
# Loss of data 🗑️
# Removing rows with missing values can reduce the dataset size and valuable information.
# Incorrect statistics 📊
# Missing values can distort calculations such as mean, median, correlation, and standard deviation.